"""initial migration

Revision ID: 0b4e888a8db9
Revises: 
Create Date: 2026-06-19 04:19:44.836447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4e888a8db9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_analyses', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_email_analyses_file_hash'), 'email_analyses', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_analyses_file_hash'), table_name='email_analyses')
    op.drop_column('email_analyses', 'file_hash')
    # ### end Alembic commands ###
